### PR TITLE
Problem sleuth spoilers

### PR DESCRIPTION
**Pull request by GiovanH**
This spoiler-gates as much problem sleuth content as we can right now. 

This includes the Map and the Science FAQ, but does not yet include Unlocks since those aren't yet data driven. It does add a todo issue to do that, though.

### CODE REVIEW

**Comment by GiovanH** [comment]
For #109

**Comment by GiovanH** [comment]
CodeQL(?) seems to be down(?), there's not actually an issue with the code failing here.

@robertbrignull, thoughts?

**Comment by robertbrignull** [comment]
@GiovanH, I'm not sure exactly what's up but it's not anything that you've done wrong. It's some kind of permissions issue related to this being a pull request from a fork. This is meant to be accounted for so that this workflow would work, but clearly it's not working as intended all of the time. I note that some PRs from your fork are working, so this isn't affecting all workflows runs.

As a short term fix, it will almost certainly work if you re-run the workflow. The re-triggered workflow run will get full write scopes because it was triggered by you (i.e. an owner of the repo) instead of from a fork (even though in this case that was also you).

**Comment by thecnoNSMB** [comment]
As I mentioned in #109, it looks as though the PS unlocks were listed in the Newsposts as they were added, starting with the 18 November 2008 post.

**Comment by thecnoNSMB** [comment]
The further I get though Problem Sleuth and the news feed, the more I realize it contains a _lot_ of information regarding when various pages were published. It announces the Science FAQ and the Blogspot (which, curiously, is spoiler-blocked by Homestuck at the moment)

**Comment by GiovanH** [comment]
> @GiovanH, I'm not sure exactly what's up but it's not anything that you've done wrong. It's some kind of permissions issue related to this being a pull request from a fork. This is meant to be accounted for so that this workflow would work, but clearly it's not working as intended all of the time. I note that some PRs from your fork are working, so this isn't affecting all workflows runs.
> 
> As a short term fix, it will almost certainly work if you re-run the workflow. The re-triggered workflow run will get full write scopes because it was triggered by you (i.e. an owner of the repo) instead of from a fork (even though in this case that was also you).

I actually did try re-running the workflow and had the same issue. As you said, I normally do this same process on this same fork without issue, which makes me think it might be a resource availability issue?

**Comment by GiovanH** [comment]
Timestamps done, should be ready. Also includes some changes to the Archive object (news gets its own file). Haven't moved extras to a json file yet

**Comment by GiovanH** [comment]
Now I have.

**Comment by GiovanH** [comment]
> @GiovanH, I'm not sure exactly what's up but it's not anything that you've done wrong. It's some kind of permissions issue related to this being a pull request from a fork. This is meant to be accounted for so that this workflow would work, but clearly it's not working as intended all of the time. I note that some PRs from your fork are working, so this isn't affecting all workflows runs.
> 
> As a short term fix, it will almost certainly work if you re-run the workflow. The re-triggered workflow run will get full write scopes because it was triggered by you (i.e. an owner of the repo) instead of from a fork (even though in this case that was also you).

@robertbrignull For the record, I did not change any configuration since this started failing. It stopped working for a while and then started working as expected again.

**Review by Bambosh — APPROVED** [review]

**Pull request merged**
