### PR TITLE
Controversial content overhaul

### PR DESCRIPTION
**Pull request by GiovanH**
New controversial content system:

- In new reader mode:
    - Controversial content may be enabled using a checkbox
    - There are extended content warnings and a dialog box that recommends you finish Homestuck first
    - Because this is new reader mode, this enables every CC without spoiling the user
    - If a mod somehow sets a controversial content option as enabled, the checkbox shows as "indeterminate" and clicking it disables all controversial content options.

- In normal mode:
    - Controversial content granular options are hidden behind a spoiler box
    - Controversial content options must be individually enabled

Also:

- Tweaks a few descriptions of controversial content and retcons
- Adds the StoryPageLink helper component
- Adds the SpoilerBox helper component

Resolves https://github.com/Bambosh/unofficial-homestuck-collection/issues/32

*Note: this contains commits from https://github.com/Bambosh/unofficial-homestuck-collection/pull/48, pull that one first!*

### CODE REVIEW

**Comment by GiovanH** [comment]
image

**Comment by GiovanH** [comment]
There should be a note on the prompt that explains that only a few pages are affected by the change either way.

**Comment by GiovanH** [comment]
Latest push has detailed page numbers and spoiler-proofing across the board, along with a dynamic settings page that reuses text as appropriate

**Review by Bambosh — CHANGES_REQUESTED** [review]

**Comment by GiovanH** [comment]
> I think we really need to emphasize that this isn't the correct/proper way to experience a first read-through

I don't know that we *can* just assert that to be true. We should make sure to communicate that that's how Andrew feels, though.

**Comment by GiovanH** [comment]
As for the specific warning language, here's what this proposal has so far:

**New Reader:**
image
image


If a new reader clicks the checkbox:
image

**Normal Reader:**

image
image
image

**

**Comment by GiovanH** [comment]
Missing the replacement music is a valid problem, but I think that "this content was changed" already implies "there is a second version of this you can see" to such an extreme tautological degree that the existing language probably suffices.

**Comment by GiovanH** [comment]
Also, looking at the interface now, maybe the "Show Affected Page Numbers" box should be aligned with the "Controversial Content" spoiler box, even though it doesn't need it? Thoughts appreciated.

**Comment by GiovanH** [comment]
Also, I changed that paragraph to 
>The Unofficial Homestuck Collection allows you to restore some material that was included in the original publication, but was since officially replaced by MSPA for various reasons. These options allow you to view those pages before they were edited. The inclusion of this content is in no way an endorsement of its quality.
to make it clear that the edits were done by the original author, not the archive.

**Pull request merged**
