### PR TITLE
Mod setting storage

### PR DESCRIPTION
**Pull request by GiovanH**
image

image

### CODE REVIEW

**Comment by GiovanH** [comment]
Also adds support for functions that generate footnote objects and namespaced mod loggers

**Comment by GiovanH** [comment]
Also includes some fun new helper scripts, significant error handling improvements

**Comment by GiovanH** [comment]
image
image

**Comment by GiovanH** [comment]
Resolves #97

**Review by Bambosh — APPROVED** [review]

**Pull request merged**
