### PR TITLE
Add Desktop file and AppStream Metadata

### PR DESCRIPTION
**Pull request by Grafcube**
This is needed for the Flatpak package. #470

### CODE REVIEW

**Comment by GiovanH** [comment]
Please configure `icons/flatpak/128x128/dev.bambosh.UnofficialHomestuckCollection.png`

**Comment by Grafcube** [comment]
> Please configure `icons/flatpak/128x128/dev.bambosh.UnofficialHomestuckCollection.png`

[dev.bambosh.UnofficialHomestuckCollection.yml](https://github.com/Grafcube/flathub/blob/d417f425b61a8a8e42047e86ab4d12f8cda78cec/dev.bambosh.UnofficialHomestuckCollection.yml#L28)
```yml
      - |
        for i in 16x16 24x24 32x32 48x48 64x64 128x128 256x256 512x512; do
          install -Dm644 build/icons/$i.png ${FLATPAK_DEST}/share/icons/hicolor/apps/$i/dev.bambosh.UnofficialHomestuckCollection.png
        done
```

The icons are being added and I see it in the build output
```
Finishing app
Exporting share/icons/hicolor/apps/16x16/dev.bambosh.UnofficialHomestuckCollection.png
Exporting share/icons/hicolor/apps/24x24/dev.bambosh.UnofficialHomestuckCollection.png
Exporting share/icons/hicolor/apps/32x32/dev.bambosh.UnofficialHomestuckCollection.png
Exporting share/icons/hicolor/apps/48x48/dev.bambosh.UnofficialHomestuckCollection.png
Exporting share/icons/hicolor/apps/64x64/dev.bambosh.UnofficialHomestuckCollection.png
Exporting share/icons/hicolor/apps/128x128/dev.bambosh.UnofficialHomestuckCollection.png
Exporting share/icons/hicolor/apps/256x256/dev.bambosh.UnofficialHomestuckCollection.png
Exporting share/icons/hicolor/apps/512x512/dev.bambosh.UnofficialHomestuckCollection.png
Exporting share/appdata/dev.bambosh.UnofficialHomestuckCollection.appdata.xml
```

I have no idea why the build failed. I'm looking through the docs for a solution.

**Comment by Grafcube** [comment]
If everything looks okay, is this ready to be merged?

I would also like to suggest updating the description in the appstream file to be a little more detailed, such as a note about the asset pack and a link to download it.

**Comment by Bambosh** [comment]
I've gone ahead and mentioned the asset pack in the description. I don't have any issues merging it, assuming whatever was happening with that build isn't going to be an issue?

**Pull request merged**
