### PR TITLE
Header is now hidden by default in fullscreen (F11) mode, with a new setting to keep it always on

### LINKED ISSUE #81: Full Screen as Full Screen
When you enter Full Screen mode, the title and tab bars are still shown.

I assume this isn't a bug, but intentional. But it would be nice for full screen to act like it does in a browser.

Thank you for your work regardless!

(This is using the Linux version at least, on Ubuntu 16.04.)

### PR DESCRIPTION
**Pull request by recordcrash**
Closes #81 

Also cleaned up some redundant template code in Settings.vue. But only some.

### CODE REVIEW

**Comment by GiovanH** [comment]
note: change the base so this targets develop (so Settings.vue works) before merging

**Comment by GiovanH** [comment]
very sorry for the git debris

**Comment by GiovanH** [comment]
After playing around with this I'm not 100% sure it should be the default. The setting could even go in oddities? @Bambosh Interested in your thoughts here

**Comment by Bambosh** [comment]
Rather than flat-out removing the header while in full screen, I think it would be interesting to expand on this so that it reappears while your cursor is the top of the screen. Firefox handles it like this, and I think it'd be a pretty good compromise.

**Comment by GiovanH** [comment]
I'm thinking it might be nice to reverse this behavior; the default is not to hide it, but there's an option that does. Plus, that option can remind people that there's a full screen mode, which is something I did not know.

**Pull request merged**
