### PR TITLE
Beyond Canon: Epilogues

### PR DESCRIPTION
**Pull request by GiovanH**

### CODE REVIEW

**Comment by GiovanH** [comment]
still needs a home widget

**Comment by Bambosh** [comment]
The default font colour changes alongside themes, which is kinda brokey. Should probably have some form of dark mode alternative for the white backdrop anyway.
image

**Review by Bambosh — DISMISSED** [review]
[See above comment](https://github.com/Bambosh/unofficial-homestuck-collection/pull/493#issuecomment-1536182585)

**Comment by GiovanH** [comment]
I feel like the epilogues probably don't need to be behind controversial content because they are actually explicitly tagged on the title page

**Review by Bambosh — APPROVED** [review]

**Pull request merged**
