### PR TITLE
Add per-theme home backgrounds

### PR DESCRIPTION
**Pull request by Niklink**
Adds unique backgrounds to existing themes for system pages. They _should_ all work fine at different resolutions.

Previews (on 1080p screen):

image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by GiovanH** [comment]
I'm not sure about the white in the scratch bg yet.

**Comment by GiovanH** [comment]
Not as scratchy, but pretty nice to look at
image

**Comment by GiovanH** [comment]
Because these are completely internal image assets, we can use webpack for a little performance optimization.

**Comment by Niklink** [comment]
Cleaned up the alt scratch colors.

image

Raw BG image:

image

**Comment by GiovanH** [comment]
image

**Review by GiovanH — APPROVED** [review]

**Review by Bambosh — APPROVED** [review]

**Pull request merged**
