### PR TITLE
News Notifications

### PR DESCRIPTION
**Pull request by GiovanH**
For #65, #117, #136

Adds a "Minor notifications" setting. Setting this sets a "subnotifications" flag, which should alert the user if anything changes, no matter how minor.

image

There's a functional implementation of newspost notifications here, but it needs some visual cleanup and hopefully some code optimization.

### CODE REVIEW

**Comment by GiovanH** [comment]
For this it would be really nice to rewrite notifications so you could send an arbitrary notification without having to define it so concretely in the registry.

**Comment by Bambosh** [comment]
Small design nitpicks:
- If multiple news posts show up between pages, the stack-up can get ludicrous (the gigapause queues up something like 9 consecutive notifications). Could be a good idea to group them into one notification.
- "New news post" doesn't sound like the best wording but I don't have anything better off the top of my head.

Some odd behavior I noticed while testing this, though a lot of it is probably unrelated to the changes made in this PR. Might drop them into their own issues if they seem important:

- Permalinks to certain newsposts fail to open the correct category. Specifically, any post with two numerals in its month column - `/news/10-17-13` fails,  while `/news/9-27-14` succeeds
- The "Show minor notifications" setting seems to be disabling itself whenever the application refreshes/restarts
- The example notification that appears when toggling "Show unlock notifications" is blank. Tangentially causes an entirely separate bug that I threw up a quick issue for #199 
image

**Comment by GiovanH** [comment]
> * If multiple news posts show up between pages, the stack-up can get ludicrous (the gigapause queues up something like 9 consecutive notifications). Could be a good idea to group them into one notification.
> * The "Show minor notifications" setting seems to be disabling itself whenever the application refreshes/restarts
> * The example notification that appears when toggling "Show unlock notifications" is blank. 
>   image

Fixed bc33bd4, fixed 14ae7fc, fixed 14ae7fc.

> * Permalinks to certain newsposts fail to open the correct category. Specifically, any post with two numerals in its month column - `/news/10-17-13` fails,  while `/news/9-27-14` succeeds

Opened #200

> * "New news post" doesn't sound like the best wording but I don't have anything better off the top of my head.

Feedback wanted!

**Comment by thecnoNSMB** [comment]
I like "New post (of news)" for the aesthetic, but "News posted" is probably the best one.

**Comment by Bambosh** [comment]
I'm also on board with "News posted". Let's go ahead with that!

**Review by Bambosh — APPROVED** [review]

**Pull request merged**
