### PR TITLE
Page navigation from pagenav updates new reader automatically (fixes multinav bugs)

### LINKED ISSUE #281: Problem Stuck progression issue on New Reader Mode during multi paths. + Bug with news notification.
Problem Stuck has a multi path at page 155 where the first path leads to page 156 followed by a death, and page 157 is the path that continues that adventure.

When using New Reader mode, you can't select page 157 and need to read page 156 to proceed. However, doing this does not unlock page 157 when you go back to page 155.
I also had minor notifications enabled. When I clicked on page 156, I got one telling me that 376 new news posts were unlocked, which wasn't true, nothing was unlocked at all.

It is possible to easily test this by adjusting New Reader Mode to page 155 and bypass the bug by adjusting it to page 157.

### PR DESCRIPTION
**Pull request by GiovanH**
For #281

### CODE REVIEW

**Comment by GiovanH** [comment]
Tell me if this is a terrible idea.

**Comment by Niklink** [comment]
What happens if you have a page 10 that links to a page 11 but also a page 999, for insane reasons? Would it set the reader progress to 999 and mess a bunch of shit up? Is this just an inherent limitation of having reader progress be tracked linearly?

**Comment by GiovanH** [comment]
It only sets the reader progress if they click the link and navigate to page 999.

**Comment by Bambosh** [comment]
Lots of flash pages don't use arrows for navigation, so there's potential for people to get stuck on those.

**Comment by GiovanH** [comment]
> Lots of flash pages don't use arrows for navigation, so there's potential for people to get stuck on those.

This doesn't replace any of the existing hardcoded navigation logic, it just adds page links as a fallback.

**Review by Bambosh — APPROVED** [review]

**Pull request merged**
